before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github(ssh_id = Sys.getenv("TRAVIS_DEPLOY_KEY", ""))'
  skip_cleanup: true

language: r
cache: packages
sudo: required

apt_packages:
    - r-cran-rjava

before_install:
    - sudo $(which R) CMD javareconf

r_packages:
    - covr

after_success:
    - Rscript -e 'library(covr); codecov()'
