language: r
cache: packages

before_install:
    - sudo $(which R) CMD javareconf
    - sudo apt install libharfbuzz-dev libfribidi-dev

r_packages:
    - covr
    - pkgdown

after_success:
    - Rscript -e 'pkgdown::deploy_site_github(ssh_id = Sys.getenv("TRAVIS_DEPLOY_KEY", ""))'
    - Rscript -e 'covr::codecov()'
