#---------------------------------------------------------------------
# Script Name:   GenotypePhenotypeFunctions.R
# Description:   Support for TASSEL GenotypePhenotype Class
# Author:        Brandon Monier & Ed buckler
# Created:       2018-11-26 at 11:14:36
# Last Modified: 2018-12-03 at 17:58:46
#--------------------------------------------------------------------

#--------------------------------------------------------------------
# Detailed Purpose:
#   The main purpose of this Rscript to support the autogenerated
#   wrappers for TASSEL plugins in TasselPluginWrappers
#--------------------------------------------------------------------


## Get GenotypePhenotype - not exported
getGenotypePhenotype <- function(jtsObject) {
  if(is(jtsObject, "TasselGenotypePhenotype")) {
    jtsObject <- jtsObject@jTasselObj
  }
  if(!is(jtsObject,"jobjRef")) return(rJava::.jnull())
  if(jtsObject %instanceof% "net.maizegenetics.phenotype.GenotypePhenotype") {
    return(jtsObject)
  } else {
    return(rJava::.jnull())
  }
}


#' @title Wrapper function of TasselGenotypePhenotype class for
#'    GenotypePhenotype combined data

#' @description Creates a Java GenotypePhenotype object which is used for
#'    \code{TasselGenotypePhenotype} object construction
#'
#' @name readGenotypePhenotype
#' @rdname readGenotypePhenotype
#'
#' @param genoPathOrObj a path to a genotype file (e.g. VCF, hmp, etc.) or
#'    TASSEL Genotype Obj
#' @param phenoPathDFOrObj a path, a data frame of phenotypic data, or TASSEL
#'    Phenotype Obj
#'
#' @importFrom rJava J
#' @importFrom rJava is.jnull
#' @importFrom rJava .jinstanceof
#' @export
readGenotypePhenotype <- function(genoPathOrObj, phenoPathDFOrObj) {
  genoObj <- getGenotypeTable(genoPathOrObj)
  if(is.jnull(genoObj)) {
    genoObj <- getGenotypeTable(readGenotypeTable(genoPathOrObj))
  }
  phenoObj <- getPhenotypeTable(phenoPathDFOrObj)
  if(is.jnull(phenoObj) & is.data.frame(phenoPathDFOrObj)) {
    phenoObj <- getPhenotypeTable(createTasselPhenotypeFromDataFrame(phenoPathDFOrObj))
  } else {
    phenoObj <- new(J("net/maizegenetics/phenotype/PhenotypeBuilder"))$fromFile(phenoPathDFOrObj)$build()$get(0L)
  }

  t <- .tasselObjectConstructor(
    new(J("net.maizegenetics.phenotype.GenotypePhenotypeBuilder"))
    $genotype(genoObj)$phenotype(phenoObj)$intersect()$build()
  )
}


#' @title Function for combining TASSEL GenotypeTable and Phenotype to GenotypePhenotype class
#' @param genotypeTable Java object of GenotypeTable
#' @param phenotype Java object of Phenotype
#'
#' @return a TASSEL GenotypePhenotype object
#' @export
combineTasselGenotypePhenotype <- function(genotypeTable, phenotype) {
  genotypeTable <- getGenotypeTable(genotypeTable)
  phenotype <- getPhenotypeTable(phenotype)
  new(J("net.maizegenetics.phenotype.GenotypePhenotypeBuilder"))$
    genotype(genotypeTable)$phenotype(phenotype)$intersect()$build()
}
