#---------------------------------------------------------------------
# Script Name:   RFunctionsSupportingTASSELPlugin.R
# Description:   Various tests with rJava
# Author:        Brandon Monier & Ed buckler
# Created:       2018-11-26 at 11:14:36
# Last Modified: 2018-12-03 at 17:58:46
#--------------------------------------------------------------------

#--------------------------------------------------------------------
# Detailed Purpose:
#    The main purpose of this Rscript to support the autogenerated wrappers
#   for TASSEL plugins in TasselPluginWrappers
#--------------------------------------------------------------------

#Uses install.packages("pryr")

settingPhenotypeAttr <- function(formula, phenotypeNameVector) {
  #formula <- y ~ x1*x2
  theTerms <- terms(formula)
  
  
}


#' Title
#'
#' @param formula Using R formula (lm) notation 
#' @param phenotypeGenotype 
#'
#' @return
#' @export
#' @details . is used for all variable, + to add one, - to exclude
#'
#' @examples

# phenotypeGenotype <- genoPhenoCombined1
# assocFormula <- . ~ dpoll
# assocFormula <- list(EarHT,EarDia) ~ dpoll 
# assocFormula <- list(EarHT,EarDia) ~ dpoll + Taxa
# assocFormula <- list(.) ~ dpoll
# assocFormula <- list(EarHT,EarDia) ~ .
# assocFormula <- list(dpoll,EarHT) ~ .
# assocFormula <- list(.) ~ . # poorly defined what is on what side - throw error
createPhenoGenoBasedOnFormula <- function(phenotypeGenotype, assocFormula) {
  # Digest a formula to set the phenotypes to one of these ATTRIBUTE_TYPE
  #enum ATTRIBUTE_TYPE {data, covariate, factor, taxa};
  #PhenotypeBuilder changeAttributeType(Map<PhenotypeAttribute, ATTRIBUTE_TYPE> changeMap) {
  jtsPheno <- getPhenotypeTable(phenotypeGenotype)
  phenoAttDf <- extractPhenotypeAttDf(jtsPheno)
  df <- emptyDFWithPhenotype(phenoAttDf)
  
  
  taxaAttNames <- phenoAttDf %>% filter(traitAttribute == "TaxaAttribute") %>% pull(traitNames)
  catAttNames <- phenoAttDf %>% filter(traitAttribute == "CategoricalAttribute") %>% pull(traitNames)
  numericAttNames <- phenoAttDf %>% filter(traitAttribute == "NumericAttribute") %>% pull(traitNames)
  labelsUsed <- terms(as.formula(assocFormula), data=df) %>% attr("term.labels")
  # cat("predictorsUsed=",predictorsUsed,"\n")
  unusedNumericNames <- setdiff(numericAttNames,labelsUsed)

  #List is used to indicate all the traits used for response
  #The list(.) is used to indicate all numeric traits available
  formulaStr <- deparse(assocFormula)
  numericAttNamesStr <- paste0("list(",paste(unusedNumericNames, collapse=","),")")
  formulaStr <- str_replace(formulaStr, "list\\(\\.\\)",numericAttNamesStr)
  assocFormula <- formula(formulaStr)
  print(assocFormula)
  
  #consider adding G or SNP as reserved if GenotypeTable present, 
  # Taxa could also be used if no co-variate, e.g. dpoll ~ Taxa
  
  term <- terms(as.formula(assocFormula), data=df)
  varNames <- as.list(attr(term,"variables"))
  varNames[[1]] <- NULL
  if(attr(term,"response") == 0) {
    stop("Define a response variable (a trait name in the phenotypes), 
         list(trait1, trait2) or list(.) for all traits")
  }
  
  responseStrV <- as.character(varNames[[attr(term,"response")]])
  responseStrV <- intersect(numericAttNames, responseStrV)
  
  covariateStrV = intersect(numericAttNames, attr(term,"term.labels"))
  categoricalStrV = intersect(catAttNames, attr(term,"term.labels"))
  taxaStrV = intersect(taxaAttNames, attr(term,"term.labels"))
  
  print(assocFormula)
  cat("Response=",responseStrV,"\n")
  cat("Covariate=",covariateStrV,"\n")
  cat("Categorical=",categoricalStrV,"\n")
  cat("Taxa=",taxaStrV,"\n")
  #TODO need to throw errors for unrecognized terms
  #TODO write code on TASSEL side to set data, covariate, etc.
}


#' @title Method for wrapping TASSEL objects in Datum and Dataset
#' @param ... a collection of TASSEL objects
#' @return a TASSEL Dataset
#' @examples 
createTasselDataSet <- function(...) {
  arguments <- list(...)
  jList <- new(J("java/util/ArrayList"))
  for(javaObj in arguments) {
    #check if they are all TASSEL jobj
    if(is(javaObj, "jobjRef") == FALSE) {
      stop(paste0("Object ",javaObj," is not of class"))
    }
    jList$add(new(J("net/maizegenetics/plugindef/Datum"),"FromR",javaObj,NULL))
  }
  new(J("net/maizegenetics/plugindef/DataSet"),jList,NULL)
}


#' Converts TASSEL dataset to List of R objects - either DataFrames or TasselGenotypePhenotype S4 Class
.dataSetToListOfRObjects <- function(jtsDataSet) {
  result <- list()
  for(i in 1:(jtsDataSet$getSize())) {
    name <- jtsDataSet$getData(i-1L)$getName()
    if(jtsDataSet$getData(i-1L)$getData() %instanceof% "net.maizegenetics.util.TableReport") {
      result[[name]] <- convertTableReportToDataFrame(jtsDataSet$getData(i-1L)$getData())
    } else {
      tasselRObj <- .tasselObjectConstructor(jtsDataSet$getData(i-1L)$getData())
      if(!is.null(tasselRObj)){
        result[[name]] <- .tasselObjectConstructor(jtsDataSet$getData(i-1L)$getData())
      }
    }
  }
  result
}
