#---------------------------------------------------------------------
# Script Name:   RFunctionsSupportingTASSELPlugin.R
# Description:   Various tests with rJava
# Author:        Brandon Monier & Ed buckler
# Created:       2018-11-26 at 11:14:36
# Last Modified: 2018-12-03 at 17:58:46
#--------------------------------------------------------------------

#--------------------------------------------------------------------
# Detailed Purpose:
#    The main purpose of this Rscript to support the autogenerated wrappers
#   for TASSEL plugins in TasselPluginWrappers
#--------------------------------------------------------------------

#Uses install.packages("pryr")

settingPhenotypeAttr <- function(formula, phenotypeNameVector) {
  #formula <- y ~ x1*x2
  theTerms <- terms(formula)
  
  
}


#' Title
#'
#' @param formula Using R formula (lm) notation 
#' @param phenotypeGenotype 
#'
#' @return
#' @export
#' @details . is used for all variable, + to add one, - to exclude
#'
#' @examples

# phenotypeGenotype <- genoPhenoCombined1
# assocFormula <- . ~ dpoll
# assocFormula <- list(EarHT,EarDia) ~ dpoll 
# assocFormula <- list(EarHT,EarDia) ~ dpoll + Taxa
# assocFormula <- list(.) ~ dpoll
# assocFormula <- list(EarHT,EarDia) ~ .
# assocFormula <- list(dpoll,EarHT) ~ .
# assocFormula <- list(.) ~ . # poorly defined what is on what side - throw error
createPhenoGenoBasedOnFormula <- function(phenotypeGenotype, assocFormula) {
  # Digest a formula to set the phenotypes to one of these ATTRIBUTE_TYPE
  #enum ATTRIBUTE_TYPE {data, covariate, factor, taxa};
  jtsPheno <- getPhenotypeTable(phenotypeGenotype)
  phenoAttDf <- extractPhenotypeAttDf(jtsPheno)
  phenoAttDf <- add_case(phenoAttDf,traitNames="G",traitTypes="g",traitAttribute="Genotype")
  df <- emptyDFWithPhenotype(phenoAttDf)
  
  # find the unused numeric attributes so they can be used with . 
  labelsUsed <- terms(as.formula(assocFormula), data=df) %>% attr("term.labels")
  unusedNumericNames <- phenoAttDf %>% filter(traitAttribute == "NumericAttribute") %>% 
    filter(!traitNames %in% labelsUsed) %>% pull(traitNames)
  
  #List is used to indicate all the traits used for response
  #The list(.) is used to indicate all numeric traits available
  listDotReplacementStr <- paste0("list(",paste(unusedNumericNames, collapse=","),")")
  assocFormula <- deparse(assocFormula) %>% 
    str_replace("list\\(\\.\\)",listDotReplacementStr) %>% 
    formula()
  print(assocFormula)
  
  #consider adding G or SNP as reserved if GenotypeTable present, 
  # Taxa could also be used if no co-variate, e.g. dpoll ~ Taxa
  
  term <- terms(as.formula(assocFormula), data=df)
  varNames <- as.list(attr(term,"variables"))
  varNames[[1]] <- NULL #removes the first one, which is a list
  if(attr(term,"response") == 0) {
    stop("Define a response variable (a trait name in the phenotypes), 
         list(trait1, trait2) or list(.) for all traits")
  }
  np <- mutate(phenoAttDf, 
         isReponse = traitNames %in% as.character(varNames[[attr(term,"response")]]),
         isPredictor = traitNames %in% attr(term,"term.labels"),
         newType = pmap_chr(list(traitAttribute, isReponse, isPredictor), tasselTypeMap)
         )
  np
  #TODO need to throw errors for unrecognized terms
  #TODO write code on TASSEL side to set data, covariate, etc.
}

tasselTypeMap <- function(traitAttribute, isResponse, isPredictor) {
  if(isResponse) {
    ifelse(traitAttribute == "NumericAttribute",return("data"),return(NULL))
  } else if(isPredictor == FALSE) {
      return(NA)
    } else {
    return(switch(traitAttribute,
      "TaxaAttribute" = "taxa",
      "NumericAttribute" = "covariate",
      "CategoricalAttribute" = "factor",
      "Genotype" = "genotype")
    )
  }
}


#' @title Method for wrapping TASSEL objects in Datum and Dataset
#' @param ... a collection of TASSEL objects
#' @return a TASSEL Dataset
#' @examples 
createTasselDataSet <- function(...) {
  arguments <- list(...)
  jList <- new(J("java/util/ArrayList"))
  for(javaObj in arguments) {
    #check if they are all TASSEL jobj
    if(is(javaObj, "jobjRef") == FALSE) {
      stop(paste0("Object ",javaObj," is not of class"))
    }
    jList$add(new(J("net/maizegenetics/plugindef/Datum"),"FromR",javaObj,NULL))
  }
  new(J("net/maizegenetics/plugindef/DataSet"),jList,NULL)
}


#' Converts TASSEL dataset to List of R objects - either DataFrames or TasselGenotypePhenotype S4 Class
.dataSetToListOfRObjects <- function(jtsDataSet) {
  result <- list()
  for(i in 1:(jtsDataSet$getSize())) {
    name <- jtsDataSet$getData(i-1L)$getName()
    if(jtsDataSet$getData(i-1L)$getData() %instanceof% "net.maizegenetics.util.TableReport") {
      result[[name]] <- convertTableReportToDataFrame(jtsDataSet$getData(i-1L)$getData())
    } else {
      tasselRObj <- .tasselObjectConstructor(jtsDataSet$getData(i-1L)$getData())
      if(!is.null(tasselRObj)){
        result[[name]] <- .tasselObjectConstructor(jtsDataSet$getData(i-1L)$getData())
      }
    }
  }
  result
}
