#---------------------------------------------------------------------
# Script Name:   TasselPluginWrappers.R
# Description:   Various tests with rJava
# Author:        Brandon Monier & Ed buckler
# Created:       2018-11-26 at 11:14:36
# Last Modified: 2018-12-21 at 15:17:16
#--------------------------------------------------------------------

#--------------------------------------------------------------------
# Detailed Purpose:
#   The main purpose of this Rscript to host to autogenerated wrappers
#   for TASSEL plugins
#--------------------------------------------------------------------

# TODO Fix filtration for TasselGenotypePhenotype datasets that contain
#      both Phenotype and Genotype objects; only returns Genotype table.
# TODO Get rid of `$FromR_Filter` from console display
filterSiteBuilderPlugin <- function(genotypeTable,
                                    siteMinCount=0,
                                    siteMinAlleleFreq=0.0,
                                    siteMaxAlleleFreq=1.0,
                                    minHeterozygous=0.0,
                                    maxHeterozygous=1.0,
                                    siteRangeFilterType="NONE",
                                    startSite=0,
                                    endSite=0
) {
  inputDataSet <- createTasselDataSet(
    .getTASSELClass(genotypeTable, "GenotypeTable")
  )
  plugin <- new(J("net.maizegenetics.analysis.filter.FilterSiteBuilderPlugin"), .jnull(), FALSE)
  plugin$setParameter("siteMinCount",toString(siteMinCount))
  plugin$setParameter("siteMinAlleleFreq",toString(siteMinAlleleFreq))
  plugin$setParameter("siteMaxAlleleFreq",toString(siteMaxAlleleFreq))
  plugin$setParameter("minHeterozygous",toString(minHeterozygous))
  plugin$setParameter("maxHeterozygous",toString(maxHeterozygous))
  plugin$setParameter("siteRangeFilterType",toString(siteRangeFilterType))
  plugin$setParameter("startSite",toString(startSite))
  plugin$setParameter("endSite",toString(endSite))
  resultDataSet <- plugin$performFunction(inputDataSet)
  .dataSetToListOfRObjects(resultDataSet)
}

filterTaxaBuilderPlugin <- function(genotypeTable,
                                    minNotMissing=0.0,
                                    minHeterozygous=0.0,
                                    maxHeterozygous=1.0,
                                    includeTaxa = TRUE,
                                    taxaList = NULL
) {
  jtsGenotypeTable <- getGenotypeTable(genotypeTable)
  if(is.jnull(jtsGenotypeTable)) {
    stop("The genotype table needs to be or contain a TASSEL GenotypeTable")
  }
  plugin <- new(J("net.maizegenetics.analysis.filter.FilterTaxaBuilderPlugin"), .jnull(), FALSE)
  plugin$setParameter("minNotMissing",toString(minNotMissing))
  plugin$setParameter("minHeterozygous",toString(minHeterozygous))
  plugin$setParameter("maxHeterozygous",toString(maxHeterozygous))
  plugin$setParameter("includeTaxa",toString(includeTaxa))
  # plugin$setParameter("taxaList",includeTaxa)
  # plugin$includeTaxa(includeTaxa)
  plugin$taxaList(taxaList)
  filteredGT <- plugin$runPlugin(jtsGenotypeTable)
  .tasselObjectConstructor(filteredGT)
}


#' @export
kinshipPlugin <- function(genotypeTable,
                          method="Centered_IBS",
                          maxAlleles=6,
                          algorithmVariation="Observed_Allele_Freq"
) {
  if(is(genotypeTable, "TasselGenotypePhenotype") == TRUE) {
    genotypeTable <- genotypeTable@jGenotypeTable
  }
  plugin <- new(J("net.maizegenetics.analysis.distance.KinshipPlugin"), .jnull(), FALSE)
  plugin$setParameter("method",toString(method))
  plugin$setParameter("maxAlleles",toString(maxAlleles))
  plugin$setParameter("algorithmVariation",toString(algorithmVariation))
  plugin$runPlugin(genotypeTable)
}

#' @export
distanceMatrixPlugin <- function(genotypeTable) {
    if(is(genotypeTable, "TasselGenotypePhenotype") == TRUE) {
        genotypeTable <- genotypeTable@jGenotypeTable
    }
    plugin <- new(J("net.maizegenetics.analysis.distance.DistanceMatrixPlugin"), .jnull(), FALSE)
    plugin$getDistanceMatrix(genotypeTable)
}


# TODO Need to support GenotypePhenotype or just Phenotype (Ed)
# TODO `plugin$setParameter("genotypeComponent", genotypeComponent)`; enum
#      not working (Ed)
# TODO `createPhenoGenoBasedOnFormula` (Ed)
fixedEffectLMPlugin <- function(formula,
                                genotypePhenotypeTable,
                                phenoOnly= FALSE,
                                saveToFile= FALSE,
                                maxP=1.0,
                                permute= FALSE,
                                nperm=0,
                                genotypeComponent=NULL,
                                minClassSize=0,
                                biallelicOnly= FALSE,
                                siteStatsOut= FALSE,
                                appendAddDom= FALSE
) {
  inputDataSet <- createTasselDataSet(
    createPhenoGenoBasedOnFormula(formula, genotypePhenotypeTable)
  )
  plugin <- new(J("net.maizegenetics.analysis.association.FixedEffectLMPlugin"), .jnull(), FALSE)
  plugin$setParameter("phenoOnly",toString(phenoOnly))
  plugin$setParameter("saveToFile",toString(saveToFile))
  plugin$setParameter("maxP",toString(maxP))
  plugin$setParameter("permute",toString(permute))
  plugin$setParameter("nperm",toString(nperm))
  #plugin$setParameter("genotypeComponent",genotypeComponent) #enum not working
  plugin$setParameter("minClassSize",toString(minClassSize))
  plugin$setParameter("biallelicOnly",toString(biallelicOnly))
  plugin$setParameter("siteStatsOut",toString(siteStatsOut))
  plugin$setParameter("appendAddDom",toString(appendAddDom))
  resultDataSet <- plugin$performFunction(inputDataSet)
  .dataSetToListOfRObjects(resultDataSet)
  # jtsDataSet <- createTasselDataSet(phenotypeOrGenotypeTable)
  # jtsResultSet <- plugin$processData(jtsDataSet)
  # dataSetToListOfDataFrame(jtsResultSet)
}
