##--------------------------------------------------------------------
# Script Name:   rjava_tests.R
# Description:   Various tests with rJava
# Author:        Brandon Monier & Ed buckler
# Created:       2018-11-26 at 11:14:36
# Last Modified: 2018-12-03 at 17:58:46
#--------------------------------------------------------------------

#--------------------------------------------------------------------
# Detailed Purpose:
#    The main purpose of this Rscript to host to autogenerated wrappers
#   for TASSEL plugins
#--------------------------------------------------------------------

# Preamble 

source("R/AllClasses.R")

filterSiteBuilderPlugin <- function(genotypeTable,
                                    siteMinCount=0,
                                    siteMinAlleleFreq=0.0,
                                    siteMaxAlleleFreq=1.0,
                                    minHeterozygous=0.0,
                                    maxHeterozygous=1.0,
                                    startSite=0,
                                    endSite=0
) {
  # Unwrap the java object if necessary
  if(is(genotypeTable,"GenotypeTable") == TRUE) {
    genotypeTable <- genotypeTable@jtsGenotypeTable
  }
  plugin <- rJava::.jnew("net.maizegenetics.analysis.filter.FilterSiteBuilderPlugin")
  plugin$setParameter("siteMinCount",toString(siteMinCount))
  plugin$setParameter("siteMinAlleleFreq",toString(siteMinAlleleFreq))
  plugin$setParameter("siteMaxAlleleFreq",toString(siteMaxAlleleFreq))
  plugin$setParameter("minHeterozygous",toString(minHeterozygous))
  plugin$setParameter("maxHeterozygous",toString(maxHeterozygous))
  plugin$setParameter("startSite",toString(startSite))
  plugin$setParameter("endSite",toString(endSite))
  
  filteredGT <- plugin$runPlugin(genotypeTable)
  #rewrap the object
  new(
    Class = "GenotypeTable",
    #todo come up with better name
    name = paste0("Filtered:"),
    jtsGenotypeTable = filteredGT
  )
}
