#---------------------------------------------------------------------
# Script Name:   TasselPluginWrappers.R
# Description:   Various tests with rJava
# Author:        Brandon Monier & Ed buckler
# Created:       2018-11-26 at 11:14:36
# Last Modified: 2018-12-03 at 17:58:46
#--------------------------------------------------------------------

#--------------------------------------------------------------------
# Detailed Purpose:
#    The main purpose of this Rscript to host to autogenerated wrappers
#   for TASSEL plugins
#--------------------------------------------------------------------

source("R/AllClasses.R")
filterSiteBuilderPlugin <- function(genotypeTable,
                                    siteMinCount=0,
                                    siteMinAlleleFreq=0.0,
                                    siteMaxAlleleFreq=1.0,
                                    minHeterozygous=0.0,
                                    maxHeterozygous=1.0,
                                    startSite=0,
                                    endSite=0
) {
  # Unwrap the java object if necessary
  if(is(genotypeTable,"GenotypeTable") == TRUE) {
    genotypeTable <- genotypeTable@jtsGenotypeTable
  }
  plugin <- rJava::.jnew("net.maizegenetics.analysis.filter.FilterSiteBuilderPlugin")
  plugin$setParameter("siteMinCount",toString(siteMinCount))
  plugin$setParameter("siteMinAlleleFreq",toString(siteMinAlleleFreq))
  plugin$setParameter("siteMaxAlleleFreq",toString(siteMaxAlleleFreq))
  plugin$setParameter("minHeterozygous",toString(minHeterozygous))
  plugin$setParameter("maxHeterozygous",toString(maxHeterozygous))
  plugin$setParameter("startSite",toString(startSite))
  plugin$setParameter("endSite",toString(endSite))
  
  filteredGT <- plugin$runPlugin(genotypeTable)
  #rewrap the object
  new(
    Class = "GenotypeTable",
    #todo come up with better name
    name = paste0("Filtered:"),
    jtsGenotypeTable = filteredGT
  )
}

filterSiteBuilderPlugin <- function(genotypeTable,
                                    siteMinCount=0,
                                    siteMinAlleleFreq=0.0,
                                    siteMaxAlleleFreq=1.0,
                                    minHeterozygous=0.0,
                                    maxHeterozygous=1.0,
                                    siteRangeFilterType="NONE",
                                    startSite=0,
                                    endSite=0
) {
  if(is(genotypeTable, "GenotypeTable") == TRUE) {
    genotypeTable <- genotypeTable@jtsGenotypeTable
  }
  plugin <- new(J("net.maizegenetics.analysis.filter.FilterSiteBuilderPlugin"), .jnull(), FALSE)
  plugin$setParameter("siteMinCount",toString(siteMinCount))
  plugin$setParameter("siteMinAlleleFreq",toString(siteMinAlleleFreq))
  plugin$setParameter("siteMaxAlleleFreq",toString(siteMaxAlleleFreq))
  plugin$setParameter("minHeterozygous",toString(minHeterozygous))
  plugin$setParameter("maxHeterozygous",toString(maxHeterozygous))
  plugin$setParameter("siteRangeFilterType",toString(siteRangeFilterType))
  plugin$setParameter("startSite",toString(startSite))
  plugin$setParameter("endSite",toString(endSite))
  filteredGT <- plugin$runPlugin(genotypeTable)
  new(
    Class = "GenotypeTable",
    name = paste0("Filtered:"),
    jtsGenotypeTable = filteredGT
  )
}

filterTaxaBuilderPlugin <- function(genotypeTable,
                                    minNotMissing=0.0,
                                    minHeterozygous=0.0,
                                    maxHeterozygous=1.0,
                                    includeTaxa = TRUE,
                                    taxaList = NULL
) {
  if(is(genotypeTable, "GenotypeTable") == TRUE) {
    genotypeTable <- genotypeTable@jtsGenotypeTable
  }
  plugin <- new(J("net.maizegenetics.analysis.filter.FilterTaxaBuilderPlugin"), .jnull(), FALSE)
  plugin$setParameter("minNotMissing",toString(minNotMissing))
  plugin$setParameter("minHeterozygous",toString(minHeterozygous))
  plugin$setParameter("maxHeterozygous",toString(maxHeterozygous))
  plugin$setParameter("includeTaxa",toString(includeTaxa))
#  plugin$setParameter("taxaList",includeTaxa)
  # plugin$includeTaxa(includeTaxa)
  plugin$taxaList(taxaList)
  filteredGT <- plugin$runPlugin(genotypeTable)
  new(
    Class = "GenotypeTable",
    name = paste0("Filtered:"),
    jtsGenotypeTable = filteredGT
  )
}

kinshipPlugin <- function(genotypeTable,
                          method="Centered_IBS",
                          maxAlleles=6,
                          algorithmVariation="Observed_Allele_Freq"
) {
  if(is(genotypeTable, "GenotypeTable") == TRUE) {
    genotypeTable <- genotypeTable@jtsGenotypeTable
  }
  plugin <- new(J("net.maizegenetics.analysis.distance.KinshipPlugin"), .jnull(), FALSE)
  plugin$setParameter("method",toString(method))
  plugin$setParameter("maxAlleles",toString(maxAlleles))
  plugin$setParameter("algorithmVariation",toString(algorithmVariation))
  plugin$runPlugin(genotypeTable)
}

fixedEffectLMPlugin <- function(phenotypeOrGenotypeTable,
                                phenoOnly=false,
                                saveToFile=false,
                                maxP=1.0,
                                permute=false,
                                nperm=0,
                                genotypeComponent=NULL,
                                minClassSize=0,
                                biallelicOnly=false,
                                siteStatsOut=false,
                                appendAddDom=false
) {
  plugin <- new(J("net.maizegenetics.analysis.association.FixedEffectLMPlugin"), .jnull(), FALSE)
  plugin$setParameter("phenoOnly",toString(phenoOnly))
  plugin$setParameter("saveToFile",toString(saveToFile))
  plugin$setParameter("maxP",toString(maxP))
  plugin$setParameter("permute",toString(permute))
  plugin$setParameter("nperm",toString(nperm))
  plugin$setParameter("genotypeComponent",toString(genotypeComponent))
  plugin$setParameter("minClassSize",toString(minClassSize))
  plugin$setParameter("biallelicOnly",toString(biallelicOnly))
  plugin$setParameter("siteStatsOut",toString(siteStatsOut))
  plugin$setParameter("appendAddDom",toString(appendAddDom))
  plugin$runPlugin(phenotypeOrGenotypeTable)
}
